name: xgenml

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: xgenml:latest
    container_name: xgenml-app
    env_file: [.env]
    environment:
      ARTIFACT_BASE_URI: ${ARTIFACT_BASE_URI}
      MLFLOW_TRACKING_URI: ${MLFLOW_TRACKING_URI}
      S3_ENDPOINT_URL: ${S3_ENDPOINT_URL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      PORT: ${PORT}
    volumes:
      - app_artifacts:/data/artifacts
    ports:
      - "${PORT}:8001"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8001/openapi.json"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s
#    depends_on:
#      minio:
#        condition: service_healthy
    profiles: ["default"]

#  minio:
#    image: quay.io/minio/minio:RELEASE.2025-01-05T00-00-00Z
#    container_name: XgenML-minio
#    command: server --console-address ":9001" /data
#    environment:
#      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
#      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
#    volumes:
#      - minio_data:/data
#    ports:
#      - "9000:9000"
#      - "9001:9001"
#    healthcheck:
#      test: ["CMD", "curl", "-fsS", "http://localhost:9000/minio/health/live"]
#      interval: 10s
#      timeout: 5s
#      retries: 10
#    profiles: ["minio"]
#
#  minio-init:
#    image: quay.io/minio/mc:RELEASE.2025-01-05T00-00-00Z
#    container_name: XgenML-minio-init
#    depends_on:
#      minio:
#        condition: service_healthy
#    entrypoint: ["/bin/sh", "-c"]
#    command: >
#      '
#      mc alias set local http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD} &&
#      mc mb -p local/${MINIO_BUCKET} || true &&
#      mc ls local &&
#      echo "MinIO init done."
#      '
#    profiles: ["minio"]


volumes:
  app_artifacts:
  #minio_data:
